services:
  db:
    image: mongo:latest
    container_name: db
    ports:
      - "27017:27017"
    volumes: 
      - ~/mongo/data:/data/db
  app:
    build:
      context: .
    container_name: app
    environment:
      - MONGO_URL=mongodb://db:27017/
    depends_on:
      - db
